spring:
  application:
    name: umbrela_api
  profiles:
    active: h2

gemini:
  api:
    url:${GEMINI_API_URL}
    key:${GEMINI_API_KEY}
  config:
    maxTokenOut: 200
    systemInstruction: "generic instruction"
    temp: 0.5
    
cloudinary:
  cloud_name: ${CLOUDiNARY_NAME}
  api_key: ${CLOUDiNARY_KEY}
  api_secret: ${CLOUDiNARY_SECRET}


