spring:
  application:
    name: umbrela_api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
    key: ${GEMINI_API_KEY}
  config:
    maxTokenOut: 200
    systemInstruction: "generic instruction"
    temp: 0.5
logging:
  level:
    org.springframework.security: TRACE
    
