spring.application.name=umbrella_api

spring.datasource.url=${DB_URL} 
spring.datasource.username=${DB_USER} 
spring.datasource.password=${DB_PASS}

gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}
